services:
  django-app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    ports:
      - 8004:8004
    networks:
      - app-network
    depends_on:
      - db
      - redis
    volumes:
      - .:/app # (host) => (docker)
    develop:
      watch:
        - action: rebuild
          path: requirements.txt
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    command:  redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - app-network
  celery:
    build:
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    networks:
      - app-network
  flower:
    build: 
      context: .
      dockerfile: dockerfiles/flower/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    ports:
      - 5555:5555
    networks:
      - app-network
networks:
  app-network:
volumes:
  pg-data:
  redis: